// Generated from reviewed Google protocol v210 downloads.
// Regenerate with docs/exchange-profiles/google-prebid-generate.py.
// Source URLs and SHA-256 digests: google-prebid-sources.json.
fn extension_schema(object_name: &str) -> Option<&'static [WireField]> {
    match object_name {
        "App" => message_schema(".com.google.doubleclick.AppExt"),
        "Audio" => message_schema(".com.google.doubleclick.AudioExt"),
        "Banner" => message_schema(".com.google.doubleclick.BannerExt"),
        "Bid" => message_schema(".com.google.doubleclick.BidExt"),
        "BidRequest" => message_schema(".com.google.doubleclick.BidRequestExt"),
        "BidResponse" => message_schema(".com.google.doubleclick.BidResponseExt"),
        "Data" => message_schema(".com.google.doubleclick.DataExt"),
        "Deal" => message_schema(".com.google.doubleclick.DealExt"),
        "Device" => message_schema(".com.google.doubleclick.DeviceExt"),
        "EventTracker" => message_schema(".com.google.doubleclick.EventTrackerExt"),
        "Geo" => message_schema(".com.google.doubleclick.GeoExt"),
        "Imp" => message_schema(".com.google.doubleclick.ImpExt"),
        "Native" => message_schema(".com.google.doubleclick.NativeExt"),
        "NativeRequest" => message_schema(".com.google.doubleclick.NativeRequestExt"),
        "Publisher" => message_schema(".com.google.doubleclick.PublisherExt"),
        "Regs" => message_schema(".com.google.doubleclick.RegsExt"),
        "Site" => message_schema(".com.google.doubleclick.SiteExt"),
        "Source" => message_schema(".com.google.doubleclick.SourceExt"),
        "UID" => message_schema(".com.google.doubleclick.UIDExt"),
        "User" => message_schema(".com.google.doubleclick.UserExt"),
        "Video" => message_schema(".com.google.doubleclick.VideoExt"),
        _ => None,
    }
}

fn message_schema(name: &str) -> Option<&'static [WireField]> {
    match name {
        ".com.google.doubleclick.AppExt" => Some(&[
            WireField {
                name: "installed_sdk",
                kind: WireType::Message(".com.google.doubleclick.AppExt.InstalledSdk"),
                repeated: true,
                oneof: None,
            },
            WireField {
                name: "inventorypartnerdomain",
                kind: WireType::String,
                repeated: false,
                oneof: None,
            },
        ]),
        ".com.google.doubleclick.AppExt.InstalledSdk" => Some(&[
            WireField {
                name: "id",
                kind: WireType::String,
                repeated: false,
                oneof: None,
            },
            WireField {
                name: "sdk_version",
                kind: WireType::Message(".com.google.doubleclick.AppExt.InstalledSdk.Version"),
                repeated: false,
                oneof: None,
            },
            WireField {
                name: "adapter_version",
                kind: WireType::Message(".com.google.doubleclick.AppExt.InstalledSdk.Version"),
                repeated: false,
                oneof: None,
            },
        ]),
        ".com.google.doubleclick.AppExt.InstalledSdk.Version" => Some(&[
            WireField {
                name: "major",
                kind: WireType::Int32,
                repeated: false,
                oneof: None,
            },
            WireField {
                name: "minor",
                kind: WireType::Int32,
                repeated: false,
                oneof: None,
            },
            WireField {
                name: "micro",
                kind: WireType::Int32,
                repeated: false,
                oneof: None,
            },
        ]),
        ".com.google.doubleclick.AudioExt" => Some(&[WireField {
            name: "bidfloor",
            kind: WireType::Number,
            repeated: false,
            oneof: None,
        }]),
        ".com.google.doubleclick.BannerExt" => Some(&[
            WireField {
                name: "clpadslot",
                kind: WireType::Message(".com.google.doubleclick.BannerExt.CollapsibleAdSlot"),
                repeated: false,
                oneof: None,
            },
            WireField {
                name: "flexslot",
                kind: WireType::Message(".com.google.doubleclick.BannerExt.FlexSlot"),
                repeated: false,
                oneof: None,
            },
            WireField {
                name: "bidfloor",
                kind: WireType::Number,
                repeated: false,
                oneof: None,
            },
        ]),
        ".com.google.doubleclick.BannerExt.CollapsibleAdSlot" => Some(&[
            WireField {
                name: "wmax",
                kind: WireType::Int32,
                repeated: false,
                oneof: None,
            },
            WireField {
                name: "hmax",
                kind: WireType::Int32,
                repeated: false,
                oneof: None,
            },
        ]),
        ".com.google.doubleclick.BannerExt.FlexSlot" => Some(&[
            WireField {
                name: "wmin",
                kind: WireType::Int32,
                repeated: false,
                oneof: None,
            },
            WireField {
                name: "wmax",
                kind: WireType::Int32,
                repeated: false,
                oneof: None,
            },
            WireField {
                name: "hmin",
                kind: WireType::Int32,
                repeated: false,
                oneof: None,
            },
            WireField {
                name: "hmax",
                kind: WireType::Int32,
                repeated: false,
                oneof: None,
            },
        ]),
        ".com.google.doubleclick.BidExt" => Some(&[
            WireField {
                name: "impression_tracking_url",
                kind: WireType::String,
                repeated: true,
                oneof: None,
            },
            WireField {
                name: "ad_choices_destination_url",
                kind: WireType::String,
                repeated: false,
                oneof: None,
            },
            WireField {
                name: "click_tracking_urls",
                kind: WireType::String,
                repeated: true,
                oneof: None,
            },
            WireField {
                name: "exchange_deal_type",
                kind: WireType::Enum(&[0, 1, 2, 3]),
                repeated: false,
                oneof: None,
            },
            WireField {
                name: "attribute",
                kind: WireType::Int32,
                repeated: true,
                oneof: None,
            },
            WireField {
                name: "amp_ad_url",
                kind: WireType::String,
                repeated: false,
                oneof: None,
            },
            WireField {
                name: "sdk_rendered_ad",
                kind: WireType::Message(".com.google.doubleclick.BidExt.SdkRenderedAd"),
                repeated: false,
                oneof: None,
            },
            WireField {
                name: "event_notification_token",
                kind: WireType::Message(".com.google.doubleclick.BidExt.EventNotificationToken"),
                repeated: false,
                oneof: None,
            },
            WireField {
                name: "restricted_category",
                kind: WireType::Int32,
                repeated: true,
                oneof: None,
            },
            WireField {
                name: "billing_id",
                kind: WireType::Int64String,
                repeated: false,
                oneof: None,
            },
            WireField {
                name: "third_party_buyer_token",
                kind: WireType::String,
                repeated: false,
                oneof: None,
            },
            WireField {
                name: "buyer_reporting_id",
                kind: WireType::String,
                repeated: false,
                oneof: None,
            },
            WireField {
                name: "fcap",
                kind: WireType::Message(".com.google.doubleclick.BidExt.FrequencyCap"),
                repeated: true,
                oneof: None,
            },
            WireField {
                name: "skadn",
                kind: WireType::Message(".com.google.doubleclick.BidExt.SKAdNetworkResponse"),
                repeated: false,
                oneof: None,
            },
            WireField {
                name: "app_promotion_type",
                kind: WireType::Enum(&[0, 1, 2, 3]),
                repeated: false,
                oneof: None,
            },
            WireField {
                name: "bid_group_id",
                kind: WireType::String,
                repeated: false,
                oneof: None,
            },
            WireField {
                name: "dsa",
                kind: WireType::Message(".com.google.doubleclick.BidExt.Dsa"),
                repeated: false,
                oneof: None,
            },
            WireField {
                name: "clpad",
                kind: WireType::Message(".com.google.doubleclick.BidExt.CollapsibleAd"),
                repeated: false,
                oneof: None,
            },
            WireField {
                name: "clickurl",
                kind: WireType::String,
                repeated: true,
                oneof: None,
            },
            WireField {
                name: "engagementclickfailureurl",
                kind: WireType::String,
                repeated: false,
                oneof: None,
            },
        ]),
        ".com.google.doubleclick.BidExt.CollapsibleAd" => Some(&[
            WireField {
                name: "wexp",
                kind: WireType::Int32,
                repeated: false,
                oneof: None,
            },
            WireField {
                name: "hexp",
                kind: WireType::Int32,
                repeated: false,
                oneof: None,
            },
        ]),
        ".com.google.doubleclick.BidExt.Dsa" => Some(&[
            WireField {
                name: "behalf",
                kind: WireType::String,
                repeated: false,
                oneof: None,
            },
            WireField {
                name: "paid",
                kind: WireType::String,
                repeated: false,
                oneof: None,
            },
            WireField {
                name: "adrender",
                kind: WireType::Flag,
                repeated: false,
                oneof: None,
            },
        ]),
        ".com.google.doubleclick.BidExt.EventNotificationToken" => Some(&[WireField {
            name: "payload",
            kind: WireType::String,
            repeated: false,
            oneof: None,
        }]),
        ".com.google.doubleclick.BidExt.FrequencyCap" => Some(&[
            WireField {
                name: "fcap_id",
                kind: WireType::String,
                repeated: false,
                oneof: None,
            },
            WireField {
                name: "time_unit",
                kind: WireType::Enum(&[0, 1, 2, 3, 4, 5]),
                repeated: false,
                oneof: None,
            },
            WireField {
                name: "time_range",
                kind: WireType::Int32,
                repeated: false,
                oneof: None,
            },
            WireField {
                name: "max_imp",
                kind: WireType::Int32,
                repeated: false,
                oneof: None,
            },
        ]),
        ".com.google.doubleclick.BidExt.SKAdNetworkResponse" => Some(&[
            WireField {
                name: "version",
                kind: WireType::String,
                repeated: false,
                oneof: None,
            },
            WireField {
                name: "network",
                kind: WireType::String,
                repeated: false,
                oneof: None,
            },
            WireField {
                name: "campaign",
                kind: WireType::String,
                repeated: false,
                oneof: None,
            },
            WireField {
                name: "sourceidentifier",
                kind: WireType::String,
                repeated: false,
                oneof: None,
            },
            WireField {
                name: "itunesitem",
                kind: WireType::String,
                repeated: false,
                oneof: None,
            },
            WireField {
                name: "productpageid",
                kind: WireType::String,
                repeated: false,
                oneof: None,
            },
            WireField {
                name: "fidelities",
                kind: WireType::Message(
                    ".com.google.doubleclick.BidExt.SKAdNetworkResponse.Fidelity",
                ),
                repeated: true,
                oneof: None,
            },
            WireField {
                name: "nonce",
                kind: WireType::String,
                repeated: false,
                oneof: None,
            },
            WireField {
                name: "sourceapp",
                kind: WireType::String,
                repeated: false,
                oneof: None,
            },
            WireField {
                name: "timestamp",
                kind: WireType::String,
                repeated: false,
                oneof: None,
            },
            WireField {
                name: "signature",
                kind: WireType::String,
                repeated: false,
                oneof: None,
            },
            WireField {
                name: "skoverlay",
                kind: WireType::Message(
                    ".com.google.doubleclick.BidExt.SKAdNetworkResponse.SKOverlay",
                ),
                repeated: false,
                oneof: None,
            },
        ]),
        ".com.google.doubleclick.BidExt.SKAdNetworkResponse.Fidelity" => Some(&[
            WireField {
                name: "fidelity",
                kind: WireType::Enum(&[0, 1]),
                repeated: false,
                oneof: None,
            },
            WireField {
                name: "nonce",
                kind: WireType::String,
                repeated: false,
                oneof: None,
            },
            WireField {
                name: "timestamp",
                kind: WireType::String,
                repeated: false,
                oneof: None,
            },
            WireField {
                name: "signature",
                kind: WireType::String,
                repeated: false,
                oneof: None,
            },
        ]),
        ".com.google.doubleclick.BidExt.SKAdNetworkResponse.SKOverlay" => Some(&[
            WireField {
                name: "delay",
                kind: WireType::Int32,
                repeated: false,
                oneof: None,
            },
            WireField {
                name: "endcarddelay",
                kind: WireType::Int32,
                repeated: false,
                oneof: None,
            },
            WireField {
                name: "dismissible",
                kind: WireType::Flag,
                repeated: false,
                oneof: None,
            },
        ]),
        ".com.google.doubleclick.BidExt.SdkRenderedAd" => Some(&[
            WireField {
                name: "id",
                kind: WireType::String,
                repeated: false,
                oneof: None,
            },
            WireField {
                name: "rendering_data",
                kind: WireType::String,
                repeated: false,
                oneof: None,
            },
            WireField {
                name: "sdk_params",
                kind: WireType::Message(".com.google.doubleclick.BidExt.SdkRenderedAd.KeyValue"),
                repeated: true,
                oneof: None,
            },
            WireField {
                name: "declared_ad",
                kind: WireType::Message(".com.google.doubleclick.BidExt.SdkRenderedAd.DeclaredAd"),
                repeated: false,
                oneof: None,
            },
        ]),
        ".com.google.doubleclick.BidExt.SdkRenderedAd.DeclaredAd" => Some(&[
            WireField {
                name: "html_snippet",
                kind: WireType::String,
                repeated: false,
                oneof: Some(0),
            },
            WireField {
                name: "video_url",
                kind: WireType::String,
                repeated: false,
                oneof: Some(0),
            },
            WireField {
                name: "video_vast_xml",
                kind: WireType::String,
                repeated: false,
                oneof: Some(0),
            },
            WireField {
                name: "native_response",
                kind: WireType::Message(".com.google.openrtb.NativeResponse"),
                repeated: false,
                oneof: Some(0),
            },
            WireField {
                name: "click_through_url",
                kind: WireType::String,
                repeated: true,
                oneof: None,
            },
        ]),
        ".com.google.doubleclick.BidExt.SdkRenderedAd.KeyValue" => Some(&[
            WireField {
                name: "key",
                kind: WireType::String,
                repeated: false,
                oneof: None,
            },
            WireField {
                name: "value",
                kind: WireType::String,
                repeated: false,
                oneof: None,
            },
        ]),
        ".com.google.doubleclick.BidRequestExt" => Some(&[
            WireField {
                name: "bid_feedback",
                kind: WireType::Message(".com.google.doubleclick.BidRequestExt.BidFeedback"),
                repeated: true,
                oneof: None,
            },
            WireField {
                name: "google_query_id",
                kind: WireType::String,
                repeated: false,
                oneof: None,
            },
            WireField {
                name: "fcap_scope",
                kind: WireType::Enum(&[0, 1, 2, 3, 4, 5]),
                repeated: false,
                oneof: None,
            },
            WireField {
                name: "privacy_treatments",
                kind: WireType::Message(".com.google.doubleclick.BidRequestExt.PrivacyTreatments"),
                repeated: false,
                oneof: None,
            },
            WireField {
                name: "expids",
                kind: WireType::String,
                repeated: true,
                oneof: None,
            },
        ]),
        ".com.google.doubleclick.BidRequestExt.BidFeedback" => Some(&[
            WireField {
                name: "request_id",
                kind: WireType::String,
                repeated: false,
                oneof: None,
            },
            WireField {
                name: "creative_status_code",
                kind: WireType::Int32,
                repeated: false,
                oneof: None,
            },
            WireField {
                name: "price",
                kind: WireType::Number,
                repeated: false,
                oneof: None,
            },
            WireField {
                name: "minimum_bid_to_win",
                kind: WireType::Number,
                repeated: false,
                oneof: None,
            },
            WireField {
                name: "billable_event_rate_bid_adjustment",
                kind: WireType::Number,
                repeated: false,
                oneof: None,
            },
            WireField {
                name: "sampled_mediation_cpm_ahead_of_auction_winner",
                kind: WireType::Number,
                repeated: false,
                oneof: None,
            },
            WireField {
                name: "event_notification_token",
                kind: WireType::Message(
                    ".com.google.doubleclick.BidRequestExt.BidFeedback.EventNotificationToken",
                ),
                repeated: false,
                oneof: None,
            },
            WireField {
                name: "buyer_creative_id",
                kind: WireType::String,
                repeated: false,
                oneof: None,
            },
        ]),
        ".com.google.doubleclick.BidRequestExt.BidFeedback.EventNotificationToken" => {
            Some(&[WireField {
                name: "payload",
                kind: WireType::String,
                repeated: false,
                oneof: None,
            }])
        }
        ".com.google.doubleclick.BidRequestExt.PrivacyTreatments" => Some(&[
            WireField {
                name: "ip",
                kind: WireType::Enum(&[0, 1, 2]),
                repeated: false,
                oneof: None,
            },
            WireField {
                name: "user_agent",
                kind: WireType::Enum(&[0, 1]),
                repeated: false,
                oneof: None,
            },
            WireField {
                name: "non_personalized_ads_reason",
                kind: WireType::Enum(&[0, 1, 2, 3]),
                repeated: true,
                oneof: None,
            },
            WireField {
                name: "allow_user_data_collection",
                kind: WireType::Flag,
                repeated: false,
                oneof: None,
            },
            WireField {
                name: "storagerestrict",
                kind: WireType::Enum(&[0, 1]),
                repeated: false,
                oneof: None,
            },
        ]),
        ".com.google.doubleclick.BidResponseExt" => Some(&[WireField {
            name: "processing_time_ms",
            kind: WireType::Int32,
            repeated: false,
            oneof: None,
        }]),
        ".com.google.doubleclick.DataExt" => Some(&[WireField {
            name: "segtax",
            kind: WireType::Int32,
            repeated: false,
            oneof: None,
        }]),
        ".com.google.doubleclick.DealExt" => Some(&[
            WireField {
                name: "deal_type",
                kind: WireType::Enum(&[0, 1, 2, 3, 4, 5]),
                repeated: false,
                oneof: None,
            },
            WireField {
                name: "must_bid",
                kind: WireType::Flag,
                repeated: false,
                oneof: None,
            },
            WireField {
                name: "publisher_blocks_overridden",
                kind: WireType::Flag,
                repeated: false,
                oneof: None,
            },
            WireField {
                name: "creative_source",
                kind: WireType::Enum(&[0, 1, 2]),
                repeated: false,
                oneof: None,
            },
            WireField {
                name: "creative_constraints",
                kind: WireType::Message(".com.google.doubleclick.DealExt.CreativeConstraints"),
                repeated: false,
                oneof: None,
            },
            WireField {
                name: "billing_id",
                kind: WireType::Int64String,
                repeated: true,
                oneof: None,
            },
        ]),
        ".com.google.doubleclick.DealExt.CreativeConstraints" => Some(&[
            WireField {
                name: "mtypes",
                kind: WireType::Enum(&[1, 2, 3, 4]),
                repeated: true,
                oneof: None,
            },
            WireField {
                name: "skippability",
                kind: WireType::Enum(&[0, 1, 2]),
                repeated: false,
                oneof: None,
            },
            WireField {
                name: "maxduration",
                kind: WireType::Int32,
                repeated: false,
                oneof: None,
            },
        ]),
        ".com.google.doubleclick.DeviceExt" => Some(&[
            WireField {
                name: "session_id",
                kind: WireType::String,
                repeated: false,
                oneof: None,
            },
            WireField {
                name: "atts",
                kind: WireType::Int32,
                repeated: false,
                oneof: None,
            },
            WireField {
                name: "ifv",
                kind: WireType::String,
                repeated: false,
                oneof: None,
            },
            WireField {
                name: "metereddata",
                kind: WireType::Flag,
                repeated: false,
                oneof: None,
            },
            WireField {
                name: "chargelevel",
                kind: WireType::Number,
                repeated: false,
                oneof: None,
            },
            WireField {
                name: "charging",
                kind: WireType::Flag,
                repeated: false,
                oneof: None,
            },
            WireField {
                name: "diskspace",
                kind: WireType::Int32,
                repeated: false,
                oneof: None,
            },
            WireField {
                name: "audioout",
                kind: WireType::Enum(&[0, 1, 2, 3, 5]),
                repeated: false,
                oneof: None,
            },
            WireField {
                name: "dooh",
                kind: WireType::Message(".com.google.doubleclick.DeviceExt.Dooh"),
                repeated: false,
                oneof: None,
            },
            WireField {
                name: "ifa_type",
                kind: WireType::String,
                repeated: false,
                oneof: None,
            },
            WireField {
                name: "memory",
                kind: WireType::Int32,
                repeated: false,
                oneof: None,
            },
            WireField {
                name: "scrollposx",
                kind: WireType::Int32,
                repeated: false,
                oneof: None,
            },
            WireField {
                name: "scrollposy",
                kind: WireType::Int32,
                repeated: false,
                oneof: None,
            },
        ]),
        ".com.google.doubleclick.DeviceExt.Dooh" => Some(&[WireField {
            name: "venuetypeid",
            kind: WireType::Int64String,
            repeated: false,
            oneof: None,
        }]),
        ".com.google.doubleclick.EventTrackerExt" => Some(&[
            WireField {
                name: "verification_parameters",
                kind: WireType::String,
                repeated: false,
                oneof: None,
            },
            WireField {
                name: "vendorKey",
                kind: WireType::String,
                repeated: false,
                oneof: None,
            },
        ]),
        ".com.google.doubleclick.GeoExt" => Some(&[WireField {
            name: "geo_criteria_id",
            kind: WireType::Int32,
            repeated: false,
            oneof: None,
        }]),
        ".com.google.doubleclick.ImpExt" => Some(&[
            WireField {
                name: "billing_id",
                kind: WireType::Int64String,
                repeated: true,
                oneof: None,
            },
            WireField {
                name: "publisher_settings_list_id",
                kind: WireType::Uint64String,
                repeated: true,
                oneof: None,
            },
            WireField {
                name: "allowed_vendor_type",
                kind: WireType::Int32,
                repeated: true,
                oneof: None,
            },
            WireField {
                name: "excluded_creatives",
                kind: WireType::Message(".com.google.doubleclick.ImpExt.ExcludedCreative"),
                repeated: true,
                oneof: None,
            },
            WireField {
                name: "dfp_ad_unit_code",
                kind: WireType::String,
                repeated: false,
                oneof: None,
            },
            WireField {
                name: "ampad",
                kind: WireType::Enum(&[1, 2, 3, 4, 5]),
                repeated: false,
                oneof: None,
            },
            WireField {
                name: "buyer_generated_request_data",
                kind: WireType::Message(".com.google.doubleclick.ImpExt.BuyerGeneratedRequestData"),
                repeated: true,
                oneof: None,
            },
            WireField {
                name: "billable_event_rate_adjustment",
                kind: WireType::Number,
                repeated: false,
                oneof: None,
            },
            WireField {
                name: "billable_event_rate_bid_adjustment",
                kind: WireType::Message(
                    ".com.google.doubleclick.ImpExt.BillableEventRateBidAdjustment",
                ),
                repeated: true,
                oneof: None,
            },
            WireField {
                name: "open_bidding",
                kind: WireType::Message(".com.google.doubleclick.ImpExt.OpenBidding"),
                repeated: false,
                oneof: None,
            },
            WireField {
                name: "allowed_restricted_category",
                kind: WireType::Int32,
                repeated: true,
                oneof: None,
            },
            WireField {
                name: "skadn",
                kind: WireType::Message(".com.google.doubleclick.ImpExt.SKAdNetworkRequest"),
                repeated: false,
                oneof: None,
            },
            WireField {
                name: "creative_enforcement_settings",
                kind: WireType::Message(
                    ".com.google.doubleclick.ImpExt.CreativeEnforcementSettings",
                ),
                repeated: false,
                oneof: None,
            },
            WireField {
                name: "is_app_open_ad",
                kind: WireType::Flag,
                repeated: false,
                oneof: None,
            },
            WireField {
                name: "ad_unit_mapping",
                kind: WireType::Message(".com.google.doubleclick.ImpExt.AdUnitMapping"),
                repeated: true,
                oneof: None,
            },
            WireField {
                name: "gpid",
                kind: WireType::String,
                repeated: false,
                oneof: None,
            },
            WireField {
                name: "jsver",
                kind: WireType::String,
                repeated: false,
                oneof: None,
            },
            WireField {
                name: "highengagement",
                kind: WireType::Flag,
                repeated: false,
                oneof: None,
            },
            WireField {
                name: "ottplacement",
                kind: WireType::Enum(&[0, 1, 2, 3, 4, 5, 99]),
                repeated: false,
                oneof: None,
            },
            WireField {
                name: "adlocx",
                kind: WireType::Int32,
                repeated: false,
                oneof: None,
            },
            WireField {
                name: "adlocy",
                kind: WireType::Int32,
                repeated: false,
                oneof: None,
            },
            WireField {
                name: "iframeorigin",
                kind: WireType::Enum(&[0, 1, 2]),
                repeated: false,
                oneof: None,
            },
        ]),
        ".com.google.doubleclick.ImpExt.AdUnitMapping" => Some(&[
            WireField {
                name: "keyvals",
                kind: WireType::Message(".com.google.doubleclick.ImpExt.AdUnitMapping.Keyval"),
                repeated: true,
                oneof: None,
            },
            WireField {
                name: "format",
                kind: WireType::Enum(&[0, 1, 2, 3, 4, 5, 6, 7]),
                repeated: false,
                oneof: None,
            },
        ]),
        ".com.google.doubleclick.ImpExt.AdUnitMapping.Keyval" => Some(&[
            WireField {
                name: "key",
                kind: WireType::String,
                repeated: false,
                oneof: None,
            },
            WireField {
                name: "value",
                kind: WireType::String,
                repeated: false,
                oneof: None,
            },
        ]),
        ".com.google.doubleclick.ImpExt.BillableEventRateBidAdjustment" => Some(&[
            WireField {
                name: "bid_adjustment",
                kind: WireType::Number,
                repeated: false,
                oneof: None,
            },
            WireField {
                name: "creative_type",
                kind: WireType::Enum(&[0, 1, 2, 3, 4]),
                repeated: false,
                oneof: None,
            },
            WireField {
                name: "sdk",
                kind: WireType::Message(".com.google.doubleclick.AppExt.InstalledSdk"),
                repeated: false,
                oneof: None,
            },
        ]),
        ".com.google.doubleclick.ImpExt.BuyerGeneratedRequestData" => Some(&[
            WireField {
                name: "source_app",
                kind: WireType::Message(
                    ".com.google.doubleclick.ImpExt.BuyerGeneratedRequestData.SourceApp",
                ),
                repeated: false,
                oneof: Some(0),
            },
            WireField {
                name: "data",
                kind: WireType::String,
                repeated: false,
                oneof: None,
            },
        ]),
        ".com.google.doubleclick.ImpExt.BuyerGeneratedRequestData.SourceApp" => {
            Some(&[WireField {
                name: "id",
                kind: WireType::String,
                repeated: false,
                oneof: None,
            }])
        }
        ".com.google.doubleclick.ImpExt.CreativeEnforcementSettings" => Some(&[
            WireField {
                name: "policy_enforcement",
                kind: WireType::Enum(&[0, 1, 2]),
                repeated: false,
                oneof: None,
            },
            WireField {
                name: "publisher_blocks_enforcement",
                kind: WireType::Enum(&[0, 1, 2]),
                repeated: false,
                oneof: None,
            },
        ]),
        ".com.google.doubleclick.ImpExt.ExcludedCreative" => Some(&[WireField {
            name: "buyer_creative_id",
            kind: WireType::String,
            repeated: false,
            oneof: None,
        }]),
        ".com.google.doubleclick.ImpExt.OpenBidding" => Some(&[WireField {
            name: "is_open_bidding",
            kind: WireType::Flag,
            repeated: false,
            oneof: None,
        }]),
        ".com.google.doubleclick.ImpExt.SKAdNetworkRequest" => Some(&[
            WireField {
                name: "versions",
                kind: WireType::String,
                repeated: true,
                oneof: None,
            },
            WireField {
                name: "sourceapp",
                kind: WireType::String,
                repeated: false,
                oneof: None,
            },
            WireField {
                name: "skadnetids",
                kind: WireType::String,
                repeated: true,
                oneof: None,
            },
            WireField {
                name: "fidelities",
                kind: WireType::Enum(&[0, 1]),
                repeated: true,
                oneof: None,
            },
            WireField {
                name: "skoverlay",
                kind: WireType::Flag,
                repeated: false,
                oneof: None,
            },
        ]),
        ".com.google.doubleclick.NativeExt" => Some(&[WireField {
            name: "bidfloor",
            kind: WireType::Number,
            repeated: false,
            oneof: None,
        }]),
        ".com.google.doubleclick.NativeRequestExt" => Some(&[
            WireField {
                name: "style_id",
                kind: WireType::Int32,
                repeated: false,
                oneof: None,
            },
            WireField {
                name: "style_height",
                kind: WireType::Int32,
                repeated: false,
                oneof: None,
            },
            WireField {
                name: "style_width",
                kind: WireType::Int32,
                repeated: false,
                oneof: None,
            },
            WireField {
                name: "style_layout_type",
                kind: WireType::Enum(&[0, 1]),
                repeated: false,
                oneof: None,
            },
            WireField {
                name: "pos",
                kind: WireType::Enum(&[0, 1, 2, 3, 4, 5, 6, 7]),
                repeated: false,
                oneof: None,
            },
        ]),
        ".com.google.doubleclick.PublisherExt" => Some(&[
            WireField {
                name: "country",
                kind: WireType::String,
                repeated: false,
                oneof: None,
            },
            WireField {
                name: "host_publisher_id",
                kind: WireType::String,
                repeated: false,
                oneof: None,
            },
            WireField {
                name: "directpay",
                kind: WireType::Flag,
                repeated: false,
                oneof: None,
            },
        ]),
        ".com.google.doubleclick.RegsExt" => Some(&[
            WireField {
                name: "gdpr",
                kind: WireType::Flag,
                repeated: false,
                oneof: None,
            },
            WireField {
                name: "lgpd",
                kind: WireType::Flag,
                repeated: false,
                oneof: None,
            },
            WireField {
                name: "dsa",
                kind: WireType::Message(".com.google.doubleclick.RegsExt.Dsa"),
                repeated: false,
                oneof: None,
            },
        ]),
        ".com.google.doubleclick.RegsExt.Dsa" => Some(&[
            WireField {
                name: "dsarequired",
                kind: WireType::Enum(&[0, 1, 2, 3]),
                repeated: false,
                oneof: None,
            },
            WireField {
                name: "pubrender",
                kind: WireType::Enum(&[0, 1, 2]),
                repeated: false,
                oneof: None,
            },
            WireField {
                name: "datatopub",
                kind: WireType::Enum(&[0, 1, 2]),
                repeated: false,
                oneof: None,
            },
        ]),
        ".com.google.doubleclick.SiteExt" => Some(&[
            WireField {
                name: "amp",
                kind: WireType::Enum(&[0, 1]),
                repeated: false,
                oneof: None,
            },
            WireField {
                name: "page_visibility",
                kind: WireType::Enum(&[0, 1, 2]),
                repeated: false,
                oneof: None,
            },
            WireField {
                name: "uact",
                kind: WireType::Message(".com.google.doubleclick.SiteExt.UserActivation"),
                repeated: false,
                oneof: None,
            },
            WireField {
                name: "ntype",
                kind: WireType::Enum(&[0, 1, 2, 3, 4]),
                repeated: false,
                oneof: None,
            },
            WireField {
                name: "is_semi_transparent_request",
                kind: WireType::Flag,
                repeated: false,
                oneof: None,
            },
            WireField {
                name: "inventorypartnerdomain",
                kind: WireType::String,
                repeated: false,
                oneof: None,
            },
        ]),
        ".com.google.doubleclick.SiteExt.UserActivation" => Some(&[
            WireField {
                name: "wasact",
                kind: WireType::Flag,
                repeated: false,
                oneof: None,
            },
            WireField {
                name: "isact",
                kind: WireType::Flag,
                repeated: false,
                oneof: None,
            },
        ]),
        ".com.google.doubleclick.SourceExt" => Some(&[
            WireField {
                name: "omidpn",
                kind: WireType::String,
                repeated: false,
                oneof: None,
            },
            WireField {
                name: "omidpv",
                kind: WireType::String,
                repeated: false,
                oneof: None,
            },
        ]),
        ".com.google.doubleclick.UIDExt" => Some(&[WireField {
            name: "stype",
            kind: WireType::String,
            repeated: false,
            oneof: None,
        }]),
        ".com.google.doubleclick.UserExt" => Some(&[
            WireField {
                name: "consented_providers_settings",
                kind: WireType::Message(
                    ".com.google.doubleclick.UserExt.ConsentedProvidersSettings",
                ),
                repeated: false,
                oneof: None,
            },
            WireField {
                name: "consent",
                kind: WireType::String,
                repeated: false,
                oneof: None,
            },
            WireField {
                name: "eids",
                kind: WireType::Message(".com.google.openrtb.BidRequest.User.EID"),
                repeated: true,
                oneof: None,
            },
            WireField {
                name: "session",
                kind: WireType::Message(".com.google.doubleclick.UserExt.Session"),
                repeated: false,
                oneof: None,
            },
            WireField {
                name: "idage",
                kind: WireType::Int32,
                repeated: false,
                oneof: None,
            },
        ]),
        ".com.google.doubleclick.UserExt.ConsentedProvidersSettings" => Some(&[
            WireField {
                name: "consented_providers",
                kind: WireType::Int64String,
                repeated: true,
                oneof: None,
            },
            WireField {
                name: "additional_consent",
                kind: WireType::String,
                repeated: false,
                oneof: None,
            },
        ]),
        ".com.google.doubleclick.UserExt.Session" => Some(&[
            WireField {
                name: "duration",
                kind: WireType::Int32,
                repeated: false,
                oneof: None,
            },
            WireField {
                name: "depth",
                kind: WireType::Int32,
                repeated: false,
                oneof: None,
            },
            WireField {
                name: "requestssinceappopen",
                kind: WireType::Int32,
                repeated: false,
                oneof: None,
            },
            WireField {
                name: "priorclicks",
                kind: WireType::Int32,
                repeated: false,
                oneof: None,
            },
        ]),
        ".com.google.doubleclick.VideoExt" => Some(&[
            WireField {
                name: "inferredplcmt",
                kind: WireType::Enum(&[0, 1, 2, 3, 4]),
                repeated: false,
                oneof: None,
            },
            WireField {
                name: "embeddedoffsite",
                kind: WireType::Flag,
                repeated: false,
                oneof: None,
            },
            WireField {
                name: "bidfloor",
                kind: WireType::Number,
                repeated: false,
                oneof: None,
            },
        ]),
        ".com.google.openrtb.BidRequest.User.EID" => Some(&[
            WireField {
                name: "source",
                kind: WireType::String,
                repeated: false,
                oneof: None,
            },
            WireField {
                name: "uids",
                kind: WireType::Message(".com.google.openrtb.BidRequest.User.EID.UID"),
                repeated: true,
                oneof: None,
            },
            WireField {
                name: "inserter",
                kind: WireType::String,
                repeated: false,
                oneof: None,
            },
            WireField {
                name: "matcher",
                kind: WireType::String,
                repeated: false,
                oneof: None,
            },
            WireField {
                name: "mm",
                kind: WireType::Int32,
                repeated: false,
                oneof: None,
            },
        ]),
        ".com.google.openrtb.BidRequest.User.EID.UID" => Some(&[
            WireField {
                name: "id",
                kind: WireType::String,
                repeated: false,
                oneof: None,
            },
            WireField {
                name: "atype",
                kind: WireType::Enum(&[1, 2, 3]),
                repeated: false,
                oneof: None,
            },
        ]),
        ".com.google.openrtb.NativeResponse" => Some(&[
            WireField {
                name: "ver",
                kind: WireType::String,
                repeated: false,
                oneof: None,
            },
            WireField {
                name: "assets",
                kind: WireType::Message(".com.google.openrtb.NativeResponse.Asset"),
                repeated: true,
                oneof: None,
            },
            WireField {
                name: "assetsurl",
                kind: WireType::String,
                repeated: false,
                oneof: None,
            },
            WireField {
                name: "dcourl",
                kind: WireType::String,
                repeated: false,
                oneof: None,
            },
            WireField {
                name: "link",
                kind: WireType::Message(".com.google.openrtb.NativeResponse.Link"),
                repeated: false,
                oneof: None,
            },
            WireField {
                name: "imptrackers",
                kind: WireType::String,
                repeated: true,
                oneof: None,
            },
            WireField {
                name: "jstracker",
                kind: WireType::String,
                repeated: false,
                oneof: None,
            },
            WireField {
                name: "eventtrackers",
                kind: WireType::Message(".com.google.openrtb.NativeResponse.EventTracker"),
                repeated: true,
                oneof: None,
            },
            WireField {
                name: "privacy",
                kind: WireType::String,
                repeated: false,
                oneof: None,
            },
        ]),
        ".com.google.openrtb.NativeResponse.Asset" => Some(&[
            WireField {
                name: "title",
                kind: WireType::Message(".com.google.openrtb.NativeResponse.Asset.Title"),
                repeated: false,
                oneof: Some(0),
            },
            WireField {
                name: "img",
                kind: WireType::Message(".com.google.openrtb.NativeResponse.Asset.Image"),
                repeated: false,
                oneof: Some(0),
            },
            WireField {
                name: "video",
                kind: WireType::Message(".com.google.openrtb.NativeResponse.Asset.Video"),
                repeated: false,
                oneof: Some(0),
            },
            WireField {
                name: "data",
                kind: WireType::Message(".com.google.openrtb.NativeResponse.Asset.Data"),
                repeated: false,
                oneof: Some(0),
            },
            WireField {
                name: "id",
                kind: WireType::Int32,
                repeated: false,
                oneof: None,
            },
            WireField {
                name: "required",
                kind: WireType::Flag,
                repeated: false,
                oneof: None,
            },
            WireField {
                name: "link",
                kind: WireType::Message(".com.google.openrtb.NativeResponse.Link"),
                repeated: false,
                oneof: None,
            },
        ]),
        ".com.google.openrtb.NativeResponse.Asset.Data" => Some(&[
            WireField {
                name: "type",
                kind: WireType::Enum(&[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]),
                repeated: false,
                oneof: None,
            },
            WireField {
                name: "len",
                kind: WireType::Int32,
                repeated: false,
                oneof: None,
            },
            WireField {
                name: "label",
                kind: WireType::String,
                repeated: false,
                oneof: None,
            },
            WireField {
                name: "value",
                kind: WireType::String,
                repeated: false,
                oneof: None,
            },
        ]),
        ".com.google.openrtb.NativeResponse.Asset.Image" => Some(&[
            WireField {
                name: "type",
                kind: WireType::Enum(&[1, 2, 3]),
                repeated: false,
                oneof: None,
            },
            WireField {
                name: "url",
                kind: WireType::String,
                repeated: false,
                oneof: None,
            },
            WireField {
                name: "w",
                kind: WireType::Int32,
                repeated: false,
                oneof: None,
            },
            WireField {
                name: "h",
                kind: WireType::Int32,
                repeated: false,
                oneof: None,
            },
        ]),
        ".com.google.openrtb.NativeResponse.Asset.Title" => Some(&[
            WireField {
                name: "text",
                kind: WireType::String,
                repeated: false,
                oneof: None,
            },
            WireField {
                name: "len",
                kind: WireType::Int32,
                repeated: false,
                oneof: None,
            },
        ]),
        ".com.google.openrtb.NativeResponse.Asset.Video" => Some(&[WireField {
            name: "vasttag",
            kind: WireType::String,
            repeated: false,
            oneof: None,
        }]),
        ".com.google.openrtb.NativeResponse.EventTracker" => Some(&[
            WireField {
                name: "event",
                kind: WireType::Enum(&[1, 2, 3, 4, 555]),
                repeated: false,
                oneof: None,
            },
            WireField {
                name: "method",
                kind: WireType::Enum(&[1, 2]),
                repeated: false,
                oneof: None,
            },
            WireField {
                name: "url",
                kind: WireType::String,
                repeated: false,
                oneof: None,
            },
        ]),
        ".com.google.openrtb.NativeResponse.Link" => Some(&[
            WireField {
                name: "url",
                kind: WireType::String,
                repeated: false,
                oneof: None,
            },
            WireField {
                name: "clicktrackers",
                kind: WireType::String,
                repeated: true,
                oneof: None,
            },
            WireField {
                name: "fallback",
                kind: WireType::String,
                repeated: false,
                oneof: None,
            },
        ]),
        _ => None,
    }
}
