#!/usr/bin/env python3
"""Synchronize profile IDs, aliases and verified directions from Rust metadata."""
from pathlib import Path
import argparse
import json
import re

parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument('--infra-dir', type=Path, help='Optional companion infra checkout to update')
args = parser.parse_args()
root = Path(__file__).resolve().parents[1]
source = (root / 'crates/rtblint-core/src/profile.rs').read_text()

def body(name):
    start = source.index('pub fn ' + name + '(')
    opening = source.index('{', start)
    depth = 1
    at = opening + 1
    while depth:
        depth += (source[at] == '{') - (source[at] == '}')
        at += 1
    return source[opening + 1:at - 1]

ids = re.findall(r'"([^"]+)"', body('ids'))
variants = dict(re.findall(r'Self::(\w+) => "([^"]+)"', body('as_str')))
labels = dict(re.findall(r'Self::(\w+) => "([^"]+)"', body('display_name')))
sources = dict(re.findall(r'Self::(\w+) => Some\("([^"]+)"\)', body('source_url')))
aliases = {}
for arm, variant in re.findall(r'((?:"[^"]+"\s*(?:\|\s*)?)+)\s*=>\s*(?:\{\s*)?Some\(Self::(\w+)\)', body('from_id')):
    for alias in re.findall(r'"([^"]+)"', arm):
        aliases[alias] = variants[variant]
assert set(ids) == set(variants.values())
assert all(aliases.get(id_) == id_ for id_ in ids)

def supported(variant, method):
    definition = body(method)
    assert '!matches!' in definition, 'Update parser when Rust support metadata changes form'
    return variant not in re.findall(r'Self::(\w+)', definition)

options = []
by_id = {id_: variant for variant, id_ in variants.items()}
for id_ in ids:
    variant = by_id[id_]
    label = {'spec': 'OpenRTB specification', 'xandr': 'Microsoft Monetize bidder', 'magnite': 'Magnite DV+ xAPI'}.get(id_, labels[variant])
    options.append({'id': id_, 'label': label, 'supportsRequest': supported(variant, 'supports_request'), 'supportsResponse': supported(variant, 'supports_response'), 'sourceUrl': sources.get(variant)})

p = root / 'npm/index.d.ts'
s = p.read_text()
s = re.sub(r'export type Profile =\n(?:  \| "[^"\n]+"\n?)+;', 'export type Profile =\n' + '\n'.join('  | ' + json.dumps(id_) for id_ in ids) + ';', s)
p.write_text(s)
profile_list = ', '.join('`' + id_ + '`' for id_ in ids)
p = root / 'README.md'
s = re.sub(r'Published profile IDs:.*?\. Select the matching direction', 'Published profile IDs: ' + profile_list + '. Select the matching direction', p.read_text())
p.write_text(s)
p = root / 'npm/README.md'
s = p.read_text()
section = s.index('## Exchange profiles')
start = s.index('\n`spec`', section)
end = s.index('\n', start + 1)
s = s[:start] + '\n' + profile_list + '.' + s[end:]
p.write_text(s)
p = root / 'proto/openadtech/rtblint/v1/rtblint.proto'
s = p.read_text()
start = s.index('  // Empty means spec. Directional profiles are separate contracts.')
start = s.index('\n', start) + 1
end = s.index('  // Xandr targets', start)
s = s[:start] + ''.join('  // ' + ', '.join(ids[index:index + 5]) + '.\n' for index in range(0, len(ids), 5)) + s[end:]
p.write_text(s)

if args.infra_dir:
    infra = args.infra_dir.resolve()
    p = infra / 'shared/profiles.ts'
    p.parent.mkdir(exist_ok=True)
    p.write_text('// Generated by rtblint scripts/sync-profile-consumers.py from Profile metadata.\n' +
        'export const PROFILE_OPTIONS = [\n' + ''.join('  ' + json.dumps(option) + ',\n' for option in options) + '] as const;\n\n' +
        'export type RtbProfile = (typeof PROFILE_OPTIONS)[number]["id"];\n' +
        'export const PROFILE_IDS = PROFILE_OPTIONS.map(({ id }) => id);\n' +
        'export const PROFILE_LABELS = Object.fromEntries(PROFILE_OPTIONS.map(({ id, label }) => [id, label])) as Record<RtbProfile, string>;\n\n' +
        'const PROFILE_ALIASES: Readonly<Partial<Record<string, RtbProfile>>> = ' + json.dumps(aliases, indent=2) + ';\n\n' +
        'export function resolveProfileId(value: string): RtbProfile | undefined {\n  return Object.hasOwn(PROFILE_ALIASES, value) ? PROFILE_ALIASES[value] : undefined;\n}\n')
    p = infra / 'apps/rtblint-web/app/page.tsx'
    p.write_text(re.sub(r'\d+ vendor and integration-direction profiles', str(len(ids) - 1) + ' vendor and integration-direction profiles', p.read_text()))
print(f'Synchronized {len(ids)} canonical profiles and {len(aliases)} canonical IDs or aliases.')
