//! Generates static Rust catalog data from the JSON object catalogs in
//! `specs/`, so the validator does no JSON parsing at runtime. The JSON files
//! remain the canonical interchange format produced by the export pipeline;
//! this build script only transcribes them into `&'static` structures.

use std::env;
use std::fmt::Write as _;
use std::fs;
use std::path::Path;

fn main() {
    println!("cargo:rerun-if-changed=specs");

    let manifest_dir = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR");
    let specs_dir = Path::new(&manifest_dir).join("specs");
    let out_path = Path::new(&env::var("OUT_DIR").expect("OUT_DIR")).join("static_catalogs.rs");

    let mut catalog_files: Vec<_> = fs::read_dir(&specs_dir)
        .expect("read specs dir")
        .filter_map(|entry| entry.ok().map(|e| e.path()))
        .filter(|path| {
            path.file_name()
                .and_then(|n| n.to_str())
                .is_some_and(|n| n.starts_with("openrtb-") && n.ends_with("-object-catalog.json"))
        })
        .collect();
    catalog_files.sort();

    let adcom_path = specs_dir.join("adcom-1.0-object-catalog.json");
    println!("cargo:rerun-if-changed={}", adcom_path.display());
    let adcom_catalog: Option<serde_json::Value> = adcom_path.exists().then(|| {
        let raw = fs::read_to_string(&adcom_path).expect("read adcom catalog json");
        serde_json::from_str(&raw).unwrap_or_else(|e| panic!("invalid adcom catalog JSON: {e}"))
    });

    let mut out = String::new();
    out.push_str("// @generated by build.rs from specs/*.json. Do not edit.\n\n");
    let mut index_entries = Vec::new();

    for (i, path) in catalog_files.iter().enumerate() {
        println!("cargo:rerun-if-changed={}", path.display());
        let raw = fs::read_to_string(path).expect("read catalog json");
        let catalog: serde_json::Value = serde_json::from_str(&raw)
            .unwrap_or_else(|e| panic!("invalid catalog JSON {}: {e}", path.display()));

        let version = catalog["version"].as_str().expect("catalog version");
        let ident = format!("CATALOG_{i}");
        index_entries.push(format!("({version:?}, &{ident})"));

        writeln!(out, "static {ident}: StaticCatalog = StaticCatalog {{").unwrap();
        writeln!(out, "    version: {version:?},").unwrap();
        writeln!(
            out,
            "    family: {:?},",
            catalog["family"].as_str().unwrap_or("")
        )
        .unwrap();
        writeln!(
            out,
            "    release_date: {:?},",
            catalog["release_date"].as_str().unwrap_or("")
        )
        .unwrap();
        writeln!(
            out,
            "    archive_path: {:?},",
            catalog["archive_path"].as_str().unwrap_or("")
        )
        .unwrap();
        out.push_str("    objects: &[\n");
        for object in catalog["objects"].as_array().expect("objects array") {
            write_object(&mut out, object);
        }
        // OpenRTB 3.0's domain layer is AdCOM: item.spec, bid.media, and
        // request.context walk these objects. Merged here so catalog lookup
        // stays a single table.
        if version == "3.0" {
            if let Some(adcom) = &adcom_catalog {
                for object in adcom["objects"].as_array().expect("adcom objects") {
                    write_object(&mut out, object);
                }
            }
        }
        out.push_str("    ],\n};\n\n");
    }

    if let Some(adcom) = &adcom_catalog {
        writeln!(
            out,
            "static ADCOM_CATALOG: StaticCatalog = StaticCatalog {{"
        )
        .unwrap();
        writeln!(
            out,
            "    version: {:?},",
            adcom["version"].as_str().unwrap_or("1.0")
        )
        .unwrap();
        writeln!(
            out,
            "    family: {:?},",
            adcom["family"].as_str().unwrap_or("1.0")
        )
        .unwrap();
        writeln!(
            out,
            "    release_date: {:?},",
            adcom["release_date"].as_str().unwrap_or("")
        )
        .unwrap();
        writeln!(
            out,
            "    archive_path: {:?},",
            adcom["archive_path"].as_str().unwrap_or("")
        )
        .unwrap();
        out.push_str("    objects: &[\n");
        for object in adcom["objects"].as_array().expect("adcom objects") {
            write_object(&mut out, object);
        }
        out.push_str("    ],\n};\n\n");
        out.push_str(
            "pub(crate) static GENERATED_ADCOM_CATALOGS: &[(&str, &StaticCatalog)] = &[(\"1.0\", &ADCOM_CATALOG)];\n\n",
        );
    } else {
        out.push_str(
            "pub(crate) static GENERATED_ADCOM_CATALOGS: &[(&str, &StaticCatalog)] = &[];\n\n",
        );
    }

    writeln!(
        out,
        "pub(crate) static GENERATED_CATALOGS: &[(&str, &StaticCatalog)] = &[{}];",
        index_entries.join(", ")
    )
    .unwrap();

    fs::write(&out_path, out).expect("write static_catalogs.rs");
}

fn write_object(out: &mut String, object: &serde_json::Value) {
    writeln!(out, "        StaticObject {{").unwrap();
    writeln!(
        out,
        "            name: {:?},",
        object["name"].as_str().unwrap()
    )
    .unwrap();
    writeln!(
        out,
        "            section: {:?},",
        object["section"].as_str().unwrap_or("")
    )
    .unwrap();
    write_citation(out, &object["citation"], "            ");
    out.push_str("            fields: &[\n");
    for field in object["fields"]
        .as_array()
        .map(|a| a.as_slice())
        .unwrap_or(&[])
    {
        write_field(out, field);
    }
    out.push_str("            ],\n        },\n");
}

fn write_field(out: &mut String, field: &serde_json::Value) {
    writeln!(out, "                StaticField {{").unwrap();
    writeln!(
        out,
        "                    name: {:?},",
        field["name"].as_str().unwrap()
    )
    .unwrap();
    let type_spec = field["type_spec"].as_str().unwrap_or("");
    writeln!(out, "                    type_spec: {type_spec:?},").unwrap();
    writeln!(
        out,
        "                    shape: ExpectedShape::{},",
        expected_shape_variant(type_spec)
    )
    .unwrap();
    writeln!(
        out,
        "                    required: {},",
        is_required(type_spec)
    )
    .unwrap();
    writeln!(
        out,
        "                    deprecated: {},",
        type_spec.to_ascii_lowercase().contains("deprecated")
    )
    .unwrap();
    writeln!(
        out,
        "                    child_object: {},",
        opt_str(field.get("child_object"))
    )
    .unwrap();
    writeln!(
        out,
        "                    adcom_list: {},",
        opt_str(field.get("adcom_list"))
    )
    .unwrap();
    match field.get("value_set").filter(|v| !v.is_null()) {
        Some(value_set) => {
            // Sorted and deduplicated so the validator can binary-search
            // the emitted slice directly.
            let mut numeric_values: Vec<i64> = value_set["values"]
                .as_array()
                .map(|a| a.iter().map(|v| v.as_i64().unwrap()).collect())
                .unwrap_or_default();
            numeric_values.sort_unstable();
            numeric_values.dedup();
            let values: Vec<String> = numeric_values.iter().map(ToString::to_string).collect();
            let minimum = value_set
                .get("minimum_inclusive")
                .and_then(|v| v.as_i64())
                .map(|v| format!("Some({v})"))
                .unwrap_or_else(|| String::from("None"));
            writeln!(
                out,
                "                    value_set: Some(StaticValueSet {{ values: &[{}], minimum_inclusive: {} }}),",
                values.join(", "),
                minimum
            )
            .unwrap();
        }
        None => out.push_str("                    value_set: None,\n"),
    }
    write_citation(out, &field["citation"], "                    ");
    out.push_str("                },\n");
}

fn write_citation(out: &mut String, citation: &serde_json::Value, indent: &str) {
    writeln!(out, "{indent}citation: StaticCitation {{").unwrap();
    writeln!(
        out,
        "{indent}    section: {:?},",
        citation["section"].as_str().unwrap_or("")
    )
    .unwrap();
    writeln!(
        out,
        "{indent}    canonical_source_file: {:?},",
        citation["canonical_source_file"].as_str().unwrap_or("")
    )
    .unwrap();
    writeln!(
        out,
        "{indent}    helper_source_file: {:?},",
        citation["helper_source_file"].as_str().unwrap_or("")
    )
    .unwrap();
    writeln!(
        out,
        "{indent}    start_line: {},",
        citation
            .get("start_line")
            .and_then(|v| v.as_u64())
            .unwrap_or(0)
    )
    .unwrap();
    writeln!(
        out,
        "{indent}    end_line: {},",
        citation
            .get("end_line")
            .and_then(|v| v.as_u64())
            .unwrap_or(0)
    )
    .unwrap();
    writeln!(out, "{indent}}},").unwrap();
}

fn opt_str(value: Option<&serde_json::Value>) -> String {
    match value.and_then(|v| v.as_str()) {
        Some(s) => format!("Some({s:?})"),
        None => String::from("None"),
    }
}

/// Mirrors the shape mapping the validator used to compute at runtime; the
/// check order matters (compound array specs before their scalar prefixes).
fn expected_shape_variant(type_spec: &str) -> &'static str {
    let lowercased = type_spec.to_ascii_lowercase();

    // The 2.0-2.5 PDFs put scope and type in separate columns, which the
    // exporter joins as "scope: <scope>; type: <type>". Only the type segment
    // describes the shape: scope prose like "recommended if geo object is not
    // supplied" would otherwise read as an object.
    let normalized = lowercased
        .split(';')
        .map(str::trim)
        .find_map(|segment| segment.strip_prefix("type:"))
        .map(|segment| segment.trim().to_string())
        .unwrap_or(lowercased);

    // Legacy phrasing spells arrays as "array of objects" / "array of strings"
    // rather than 2.6's "object array" / "string array".
    if let Some(element) = normalized.split("array of").nth(1) {
        let element = element.trim();
        // "array of BrandVersion objects", not prose that later says "each object".
        if element.starts_with("object") || element.contains(" objects") {
            return "ObjectArray";
        }
        if element.starts_with("string") {
            return "StringArray";
        }
        if element.starts_with("integer") {
            return "IntegerArray";
        }
        if element.starts_with("float") {
            return "FloatArray";
        }
        if element.starts_with("boolean") {
            return "BooleanArray";
        }
        return "AnyArray";
    }

    // "string, array" is how the 2.6 snapshots spell DOOH.venuetype.
    if let Some(element) = normalized
        .split(", array")
        .next()
        .filter(|element| element.len() < normalized.len() && !element.trim().is_empty())
    {
        let element = element.trim();
        if element.ends_with("object") {
            return "ObjectArray";
        }
        if element.ends_with("string") {
            return "StringArray";
        }
        if element.ends_with("integer") {
            return "IntegerArray";
        }
        if element.ends_with("float") {
            return "FloatArray";
        }
    }

    if normalized.contains("object array") {
        return "ObjectArray";
    }
    if normalized.contains("string array") {
        return "StringArray";
    }
    if normalized.contains("integer array") {
        return "IntegerArray";
    }
    if normalized.contains("float array") {
        return "FloatArray";
    }
    if normalized.contains("boolean array") {
        return "BooleanArray";
    }
    if normalized.contains("enum array") {
        return "AnyArray";
    }
    if normalized.contains("object") {
        return "Object";
    }
    if normalized.contains("string") {
        return "String";
    }
    if normalized.contains("integer") {
        return "Integer";
    }
    if normalized.contains("float") {
        return "Float";
    }
    if normalized.contains("boolean") {
        return "Boolean";
    }

    // Short and misspelled type words the spec tables actually contain:
    // "int" (Content.livestream, Content.realtime, EID.mm, Content.gtax),
    // "inpteger" (Video.minbitrate across three 2.6 snapshots), "srting"
    // (Site.page). Left unmapped these fields carry Unknown shape, which
    // silently disables type checking on them, so a boolean or a string
    // where the spec wants an integer passes unnoticed. Matched as whole
    // words, since "int" is a substring of "point" and of "printed".
    for token in normalized.split(|character: char| !character.is_ascii_alphanumeric()) {
        match token {
            "int" | "inpteger" => return "Integer",
            "srting" => return "String",
            _ => {}
        }
    }

    "Unknown"
}

/// A field is unconditionally required only when the type column says so as
/// its own segment ("string; required", "scope: required; type: ...").
/// Conditional phrasings from the spec's prose ("required for Flex Ads",
/// "required if sourcetype is present") must not count, and neither does
/// "required *": the asterisk is the 3.0 spec's footnote for "exactly one of
/// these", which the validator enforces as an envelope rule instead.
fn is_required(type_spec: &str) -> bool {
    type_spec
        .to_ascii_lowercase()
        .split(';')
        .map(str::trim)
        .any(|segment| segment == "required" || segment == "scope: required")
}
